//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GDDSVSPEntities : DbContext
    {
        public GDDSVSPEntities()
            : base("name=GDDSVSPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Degree> Degree { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Dormitory> Dormitory { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<FunctionalGroup> FunctionalGroup { get; set; }
        public virtual DbSet<JobType> JobType { get; set; }
        public virtual DbSet<Manager> Manager { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Option> Option { get; set; }
        public virtual DbSet<OptionType> OptionType { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<Questionnaire> Questionnaire { get; set; }
        public virtual DbSet<QuestionnaireSubmission> QuestionnaireSubmission { get; set; }
        public virtual DbSet<QuestionOptionMapping> QuestionOptionMapping { get; set; }
        public virtual DbSet<QuestionType> QuestionType { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RoleMenuMapping> RoleMenuMapping { get; set; }
        public virtual DbSet<QuestionnaireType> QuestionnaireType { get; set; }
        public virtual DbSet<QuestionAnswerMapping> QuestionAnswerMapping { get; set; }
    }
}
