//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionAnswerMapping
    {
        public System.Guid QuestionAnswerID { get; set; }
        public Nullable<System.Guid> QuestionID { get; set; }
        public Nullable<System.Guid> OptionID { get; set; }
        public string OptionReason { get; set; }
        public Nullable<int> IsDel { get; set; }
        public Nullable<System.Guid> EmployeeID { get; set; }
        public Nullable<System.Guid> DepartmentID { get; set; }
        public Nullable<System.Guid> FunctionalGroupID { get; set; }
        public Nullable<System.Guid> QuestionnaireID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
