//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Button
    {
        public System.Guid ButtonID { get; set; }
        public string BtnCode { get; set; }
        public string BtnName { get; set; }
        public Nullable<int> BtnOrder { get; set; }
        public string BtnDescribe { get; set; }
        public string BtnIcon { get; set; }
        public Nullable<int> BtnType { get; set; }
        public Nullable<int> IsDel { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public string Modifier { get; set; }
        public Nullable<int> ShowType { get; set; }
    }
}
